import Router from 'express';
import ContactController from '#controllers/ContactController';
import ContactRepo from '#contacts/contact.repo';
import ContactService from '#contacts/contact.service';
import connectionPool from '#db';
const contactRouter = Router();
const ContactRepoInstance = ContactRepo(connectionPool);
const ContactServiceInstance = ContactService(ContactRepoInstance);
const ContactCtrlInstance = ContactController(ContactServiceInstance);
contactRouter.post('/', ContactCtrlInstance.createContact);
contactRouter.get('/', ContactCtrlInstance.fetchContacts);
export default contactRouter;